#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: ./scripts/release-prepare-signing-keychain.sh [--output-dir DIR]

Create a temporary keychain for non-interactive macOS signing and write
SIGNING_KEYCHAIN_PATH exports to <output-dir>/signing-keychain.env.

Certificate source modes:
  1. APPLE_CERTIFICATE + APPLE_CERTIFICATE_PASSWORD
     - APPLE_CERTIFICATE must contain base64-encoded PKCS#12 bytes.
  2. CERT_PATH + APPLE_CERTIFICATE_PASSWORD
     - CERT_PATH points to a PKCS#12 file to import.
  3. SOURCE_KEYCHAIN_PATH
     - export identities from an installed macOS keychain into a temporary
       PKCS#12 file, then import them into the temporary signing keychain.

Optional environment variables:
  OUTPUT_DIR             Override the output directory.
  KEYCHAIN_PATH          Override the created keychain path.
  KEYCHAIN_PASSWORD      Password for the created keychain. Auto-generated by default.
  SOURCE_KEYCHAIN_PATH   Source keychain to export from in mode 3.
  CERT_PATH              PKCS#12 path to import in mode 2.

Outputs:
  <output-dir>/signing.keychain-db
  <output-dir>/signing-keychain.env
  <output-dir>/codesigning-identities.txt
  <output-dir>/README.txt

Example (installed cert in System.keychain):
  OUTPUT_DIR="$(mktemp -d /tmp/pnevma-signing.XXXXXX)" \
  SOURCE_KEYCHAIN_PATH="/Library/Keychains/System.keychain" \
  ./scripts/release-prepare-signing-keychain.sh
  source "$OUTPUT_DIR/signing-keychain.env"
EOF
}

OUTPUT_DIR="${OUTPUT_DIR:-}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)
      shift
      OUTPUT_DIR="${1:-}"
      if [[ -z "$OUTPUT_DIR" ]]; then
        echo "--output-dir requires a value" >&2
        exit 2
      fi
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if ! command -v security >/dev/null 2>&1; then
  echo "security is required" >&2
  exit 2
fi

random_password() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
}

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$(mktemp -d "${TMPDIR:-/tmp}/pnevma-signing.XXXXXX")"
else
  mkdir -p "$OUTPUT_DIR"
fi

KEYCHAIN_PATH="${KEYCHAIN_PATH:-$OUTPUT_DIR/signing.keychain-db}"
ENV_PATH="$OUTPUT_DIR/signing-keychain.env"
IDENTITIES_PATH="$OUTPUT_DIR/codesigning-identities.txt"
README_PATH="$OUTPUT_DIR/README.txt"
KEYCHAIN_PASSWORD="${KEYCHAIN_PASSWORD:-$(random_password)}"

TEMP_CERT_PATH=""

cleanup() {
  if [[ -n "$TEMP_CERT_PATH" && -f "$TEMP_CERT_PATH" ]]; then
    rm -f "$TEMP_CERT_PATH"
  fi
}
trap cleanup EXIT

import_mode=""
CERT_IMPORT_PATH=""
CERT_IMPORT_PASSWORD=""

if [[ -n "${APPLE_CERTIFICATE:-}" ]]; then
  TEMP_CERT_PATH="$OUTPUT_DIR/certificate.p12"
  APPLE_CERTIFICATE="$APPLE_CERTIFICATE" \
  TEMP_CERT_PATH="$TEMP_CERT_PATH" \
  python3 - <<'PY'
import base64
import os
from pathlib import Path

raw = os.environ["APPLE_CERTIFICATE"]
target = Path(os.environ["TEMP_CERT_PATH"])
target.write_bytes(base64.b64decode(raw))
PY
  CERT_IMPORT_PATH="$TEMP_CERT_PATH"
  CERT_IMPORT_PASSWORD="${APPLE_CERTIFICATE_PASSWORD:-}"
  import_mode="base64-env"
elif [[ -n "${CERT_PATH:-}" ]]; then
  CERT_IMPORT_PATH="$CERT_PATH"
  CERT_IMPORT_PASSWORD="${APPLE_CERTIFICATE_PASSWORD:-}"
  import_mode="cert-path"
elif [[ -n "${SOURCE_KEYCHAIN_PATH:-}" ]]; then
  TEMP_CERT_PATH="$OUTPUT_DIR/exported-identities.p12"
  TEMP_CERT_PASSWORD="$(random_password)"
  security export \
    -k "$SOURCE_KEYCHAIN_PATH" \
    -t identities \
    -f pkcs12 \
    -P "$TEMP_CERT_PASSWORD" \
    -o "$TEMP_CERT_PATH" >/dev/null
  CERT_IMPORT_PATH="$TEMP_CERT_PATH"
  CERT_IMPORT_PASSWORD="$TEMP_CERT_PASSWORD"
  import_mode="source-keychain"
else
  echo "No certificate source configured. Set APPLE_CERTIFICATE, CERT_PATH, or SOURCE_KEYCHAIN_PATH." >&2
  exit 1
fi

if [[ ! -f "$CERT_IMPORT_PATH" ]]; then
  echo "Certificate bundle not found at $CERT_IMPORT_PATH" >&2
  exit 1
fi

if [[ -z "$CERT_IMPORT_PASSWORD" ]]; then
  echo "APPLE_CERTIFICATE_PASSWORD is required for the selected certificate source" >&2
  exit 1
fi

security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
security list-keychains -d user -s "$KEYCHAIN_PATH"
security default-keychain -d user -s "$KEYCHAIN_PATH"
security import \
  "$CERT_IMPORT_PATH" \
  -P "$CERT_IMPORT_PASSWORD" \
  -A \
  -T /usr/bin/codesign \
  -T /usr/bin/security \
  -t cert \
  -f pkcs12 \
  -k "$KEYCHAIN_PATH" >/dev/null
security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH" >/dev/null
security find-identity -v -p codesigning "$KEYCHAIN_PATH" >"$IDENTITIES_PATH"

if ! grep -q "valid identities found" "$IDENTITIES_PATH"; then
  echo "No codesigning identities found in temporary keychain $KEYCHAIN_PATH" >&2
  cat "$IDENTITIES_PATH" >&2
  exit 1
fi

if [[ -n "${APPLE_SIGNING_IDENTITY:-}" ]] && ! grep -Fq "\"$APPLE_SIGNING_IDENTITY\"" "$IDENTITIES_PATH"; then
  echo "Requested signing identity not found in temporary keychain: $APPLE_SIGNING_IDENTITY" >&2
  cat "$IDENTITIES_PATH" >&2
  exit 1
fi

cat >"$ENV_PATH" <<EOF
export SIGNING_KEYCHAIN_PATH="$KEYCHAIN_PATH"
EOF

cat >"$README_PATH" <<EOF
Temporary signing keychain created for Pnevma release signing.

Mode: $import_mode
Keychain: $KEYCHAIN_PATH
Env file: $ENV_PATH

Next step:
  source "$ENV_PATH"

Then run:
  APPLE_SIGNING_IDENTITY="Developer ID Application: ..." \\
  ./scripts/release-signed-candidate.sh

Cleanup when finished:
  rm -rf "$OUTPUT_DIR"
EOF

echo "Prepared temporary signing keychain"
echo "  mode: $import_mode"
echo "  keychain: $KEYCHAIN_PATH"
echo "  env file: $ENV_PATH"
echo "  next: source \"$ENV_PATH\""
