/* Auto-generated by cbindgen — do not edit */

#ifndef PNEVMA_BRIDGE_H
#define PNEVMA_BRIDGE_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle holding all Pnevma runtime state.
 */
typedef struct PnevmaHandle PnevmaHandle;

/**
 * Callback for Rust→Swift event forwarding.
 */
typedef void (*EventCallback)(const char *event, const char *payload_json, void *ctx);

/**
 * Result struct returned by synchronous FFI calls.
 */
typedef struct PnevmaResult {
  int32_t ok;
  const char *data;
  uintptr_t len;
} PnevmaResult;

/**
 * Callback for async call completion.
 */
typedef void (*AsyncCallback)(const struct PnevmaResult *result, void *ctx);

/**
 * Callback for releasing async callback context.
 */
typedef void (*AsyncContextRelease)(void *ctx);

/**
 * Callback for high-frequency session PTY output.
 */
typedef void (*SessionOutputCallback)(const char *session_id,
                                      const uint8_t *data,
                                      uintptr_t len,
                                      void *ctx);

/**
 * Create a new Pnevma runtime handle.
 *
 * `cb` receives all Rust-emitted events (e.g. "task_updated", "session_output").
 * `ctx` is an opaque pointer forwarded to every callback invocation.
 *
 * Returns NULL on failure. The caller must eventually call `pnevma_destroy`.
 *
 * # Safety
 *
 * `ctx` must be valid for the lifetime of the returned handle (until
 * `pnevma_destroy` is called). `cb` must be safe to call from any thread.
 */
 struct PnevmaHandle *pnevma_create(EventCallback cb, void *ctx);

/**
 * Destroy a Pnevma handle, shutting down all background tasks.
 *
 * After this call, the handle pointer is invalid.
 *
 * # Safety
 *
 * `handle` must be a pointer returned by `pnevma_create` that has not yet been
 * destroyed, or NULL (which is a no-op).
 */
 void pnevma_destroy(struct PnevmaHandle *handle);

/**
 * Synchronous RPC call. Blocks until the command completes.
 *
 * **Must be called from a background thread** — never from the main thread.
 *
 * Returns a heap-allocated `PnevmaResult`. Caller must free with `pnevma_free_result`.
 *
 * `params_json` must point to a valid allocation of at least `params_len`
 * bytes. Passing a length exceeding the allocation is undefined behavior.
 * NULL is valid when `params_len` is 0 (treated as empty params).
 *
 * # Safety
 *
 * `handle` must be a live pointer returned by `pnevma_create`. `method` must
 * be a valid null-terminated C string. `params_json` must point to at least
 * `params_len` valid bytes, or be NULL when `params_len` is 0.
 */

struct PnevmaResult *pnevma_call(struct PnevmaHandle *handle,
                                 const char *method,
                                 const char *params_json,
                                 uintptr_t params_len);

/**
 * Asynchronous RPC call. Returns immediately; the callback is invoked on
 * completion from a background thread.
 *
 * The `PnevmaResult*` passed to the callback is valid only for the duration
 * of the callback. Copy any data you need before returning. The result is
 * freed automatically by Rust after the callback returns — do NOT call
 * `pnevma_free_result` on it.
 *
 * `params_json` must point to a valid allocation of at least `params_len`
 * bytes. Passing a length exceeding the allocation is undefined behavior.
 *
 * LIFETIME CONTRACT: `cb_ctx` must remain valid until the callback fires or
 * its `release_cb` is invoked. Destroying the handle cancels pending async
 * calls without invoking their completion callbacks, but still invokes
 * `release_cb` exactly once for each pending callback. `release_cb` must be a
 * valid function pointer; use a no-op function when `cb_ctx` requires no
 * cleanup. Passing NULL is valid only if both callbacks handle NULL context.
 *
 * # Safety
 *
 * `handle` must be a live pointer returned by `pnevma_create`. `method` must
 * be a valid null-terminated C string. `params_json` must point to at least
 * `params_len` valid bytes, or be NULL when `params_len` is 0. `cb`,
 * `release_cb` must be valid function pointers. `cb_ctx` must remain valid
 * until `cb` or `release_cb` is invoked.
 */

void pnevma_call_async(struct PnevmaHandle *handle,
                       const char *method,
                       const char *params_json,
                       uintptr_t params_len,
                       AsyncCallback cb,
                       void *cb_ctx,
                       AsyncContextRelease release_cb);

/**
 * Free a `PnevmaResult` returned by `pnevma_call`.
 *
 * Safe to call with NULL.
 *
 * # Safety
 *
 * `result` must be a pointer returned by `pnevma_call`, or NULL.
 */
 void pnevma_free_result(struct PnevmaResult *result);

/**
 * Register a callback for high-frequency session PTY output.
 *
 * This bypasses the JSON event system for performance. The callback receives
 * raw bytes directly from the PTY.
 *
 * LIFETIME CONTRACT: `ctx` must remain valid for as long as the callback
 * is registered (i.e., until a new callback is registered or the handle
 * is destroyed). Unregistering or destroying the handle waits for any
 * in-flight callback snapshots to finish before returning. The caller must
 * NOT free or mutate the context while the callback may be invoked from a
 * background thread.
 *
 * # Safety
 *
 * `handle` must be a live pointer returned by `pnevma_create`. `cb` must be a
 * valid function pointer (or zero to unregister). `ctx` must remain valid for
 * the lifetime of the registration.
 */

void pnevma_set_session_output_callback(struct PnevmaHandle *handle,
                                        SessionOutputCallback cb,
                                        void *ctx);

#endif  /* PNEVMA_BRIDGE_H */
