/* Auto-generated by cbindgen — do not edit */

#ifndef PNEVMA_BRIDGE_H
#define PNEVMA_BRIDGE_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle holding all Pnevma runtime state.
 */
typedef struct PnevmaHandle PnevmaHandle;

/**
 * Callback for Rust→Swift event forwarding.
 */
typedef void (*EventCallback)(const char *event, const char *payload_json, void *ctx);

/**
 * Result struct returned by synchronous FFI calls.
 */
typedef struct PnevmaResult {
  int32_t ok;
  const char *data;
  uintptr_t len;
} PnevmaResult;

/**
 * Callback for async call completion.
 */
typedef void (*AsyncCallback)(const struct PnevmaResult *result, void *ctx);

/**
 * Callback for high-frequency session PTY output.
 */
typedef void (*SessionOutputCallback)(const char *session_id,
                                      const uint8_t *data,
                                      uintptr_t len,
                                      void *ctx);

/**
 * Create a new Pnevma runtime handle.
 *
 * `cb` receives all Rust-emitted events (e.g. "task_updated", "session_output").
 * `ctx` is an opaque pointer forwarded to every callback invocation.
 *
 * Returns NULL on failure. The caller must eventually call `pnevma_destroy`.
 */
 struct PnevmaHandle *pnevma_create(EventCallback cb, void *ctx);

/**
 * Destroy a Pnevma handle, shutting down all background tasks.
 *
 * After this call, the handle pointer is invalid.
 */
 void pnevma_destroy(struct PnevmaHandle *handle);

/**
 * Synchronous RPC call. Blocks until the command completes.
 *
 * **Must be called from a background thread** — never from the main thread.
 *
 * Returns a heap-allocated `PnevmaResult`. Caller must free with `pnevma_free_result`.
 */

struct PnevmaResult *pnevma_call(struct PnevmaHandle *handle,
                                 const char *method,
                                 const char *params_json,
                                 uintptr_t _len);

/**
 * Asynchronous RPC call. Returns immediately; the callback is invoked on
 * completion from a background thread.
 *
 * The `PnevmaResult*` passed to the callback is valid only for the duration
 * of the callback. Copy any data you need before returning.
 */

void pnevma_call_async(struct PnevmaHandle *handle,
                       const char *method,
                       const char *params_json,
                       uintptr_t _len,
                       AsyncCallback cb,
                       void *cb_ctx);

/**
 * Free a `PnevmaResult` returned by `pnevma_call`.
 *
 * Safe to call with NULL.
 *
 * # Safety
 *
 * `result` must be a pointer returned by `pnevma_call`, or NULL.
 */
 void pnevma_free_result(struct PnevmaResult *result);

/**
 * Register a callback for high-frequency session PTY output.
 *
 * This bypasses the JSON event system for performance. The callback receives
 * raw bytes directly from the PTY.
 */

void pnevma_set_session_output_callback(struct PnevmaHandle *handle,
                                        SessionOutputCallback cb,
                                        void *ctx);

#endif  /* PNEVMA_BRIDGE_H */
